services:
  redis:
    container_name: serialization_study_redis
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 2s
      timeout: 3s
      retries: 60
    networks:
      - serialization-study
  mysql:
    container_name: serialization_study_mysql
    image: mysql:8
    ports:
      - '3307:3306'
    environment:
      TZ: 'Asia/Seoul'
      MYSQL_DATABASE: serialization_study
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./infra/mysql/data:/var/lib/mysql
    networks:
      - serialization-study
networks:
  serialization-study:
    name: serialization-study
    driver: bridge
