spring.config.activate.on-profile: default
server:
  port: 8081

spring:
  webflux:
    base-path: /api
  config:
    import:
      - domain.yaml

springdoc:
  swagger-ui:
    path: /docs

---
spring.config.activate.on-profile: dev